# Generated by Django 5.2.6 on 2025-09-08 14:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        help_text="Client-provided event ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                (
                    "event_properties",
                    models.JSONField(
                        default=dict, help_text="Flexible event data storage"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="projects.eventsource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "indexes": [
                    models.Index(
                        fields=["project", "timestamp"],
                        name="events_project_542748_idx",
                    ),
                    models.Index(
                        fields=["project", "event_name", "timestamp"],
                        name="events_project_1d52a7_idx",
                    ),
                    models.Index(
                        fields=["project", "event_source", "timestamp"],
                        name="events_project_bdfa02_idx",
                    ),
                    models.Index(
                        fields=["project", "user_id", "timestamp"],
                        name="events_project_e8a1fb_idx",
                    ),
                    models.Index(
                        fields=["project", "session_id", "timestamp"],
                        name="events_project_90ffc7_idx",
                    ),
                    models.Index(
                        fields=["project", "event_name"],
                        name="events_project_d71488_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="events_timesta_ba2f67_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="events_created_9e2206_idx"
                    ),
                    models.Index(
                        fields=["processed_at"], name="events_process_8dc733_idx"
                    ),
                ],
            },
        ),
    ]
