# Generated by Django 5.2.6 on 2025-09-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyEventAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("unique_sessions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "event_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.eventsource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "date"],
                        name="events_dail_project_907bc6_idx",
                    ),
                    models.Index(
                        fields=["project", "event_name", "date"],
                        name="events_dail_project_214267_idx",
                    ),
                    models.Index(
                        fields=["date", "event_count"],
                        name="events_dail_date_feb12b_idx",
                    ),
                ],
                "unique_together": {("project", "event_source", "event_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="HourlyEventAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("unique_sessions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime_hour", models.DateTimeField(db_index=True)),
                (
                    "event_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.eventsource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "datetime_hour"],
                        name="events_hour_project_b07758_idx",
                    ),
                    models.Index(
                        fields=["project", "event_name", "datetime_hour"],
                        name="events_hour_project_180f7f_idx",
                    ),
                    models.Index(
                        fields=["datetime_hour", "event_count"],
                        name="events_hour_datetim_8b71e8_idx",
                    ),
                ],
                "unique_together": {
                    ("project", "event_source", "event_name", "datetime_hour")
                },
            },
        ),
        migrations.CreateModel(
            name="ProjectDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("unique_sessions", models.PositiveIntegerField(default=0)),
                ("unique_event_names", models.PositiveIntegerField(default=0)),
                ("source_breakdown", models.JSONField(default=dict)),
                ("top_events", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "total_events"],
                        name="events_proj_date_92a492_idx",
                    ),
                    models.Index(
                        fields=["project", "date"],
                        name="events_proj_project_901863_idx",
                    ),
                ],
                "unique_together": {("project", "date")},
            },
        ),
    ]
