# Generated by Django 5.2.6 on 2025-09-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_add_aggregation_models"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiveMinuteEventAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("unique_sessions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime_5min", models.DateTimeField(db_index=True)),
                (
                    "event_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.eventsource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_aggregations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "datetime_5min"],
                        name="events_five_project_32e51e_idx",
                    ),
                    models.Index(
                        fields=["project", "event_name", "datetime_5min"],
                        name="events_five_project_141fcb_idx",
                    ),
                    models.Index(
                        fields=["datetime_5min", "event_count"],
                        name="events_five_datetim_d308d4_idx",
                    ),
                    models.Index(
                        fields=["-datetime_5min", "project"],
                        name="events_five_datetim_d9b32c_idx",
                    ),
                ],
                "unique_together": {
                    ("project", "event_source", "event_name", "datetime_5min")
                },
            },
        ),
    ]
