# Generated by Django 5.2.6 on 2025-09-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="projects_api_key_c7f915_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="api_key",
        ),
        migrations.AddField(
            model_name="project",
            name="private_api_key",
            field=models.CharField(
                default="sa_priv_temp_private",
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="public_api_key",
            field=models.CharField(
                default="sa_temp_public", editable=False, max_length=64, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["public_api_key"], name="projects_public__a570c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["private_api_key"], name="projects_private_1a45c6_idx"
            ),
        ),
    ]
